### ISSUE TITLE
Cannot clone cpython hg: stream ended unexpectedly

### ISSUE THREAD

**Issue by native-api** [python/pythondotorg#811]
```
$ hg clone --debug https://hg.python.org/cpython
using https://hg.python.org/cpython
sending capabilities command
hg.python.org certificate successfully verified
destination directory: cpython
query 1; heads
sending batch command
requesting all changes
sending getbundle command
add changeset <...>
add changeset <...>
<...>
bundle2-input-part: total payload size 31948622
bundle2-input-bundle: 0 parts total
transaction abort!
rollback completed
abort: stream ended unexpectedly (got 0 bytes, expected 4)
```

The error happens at different points (different "total payload size") each time.
Updating to `hg 3.5+5` didn't help.
I've been having this issue since at least the day before yesterday.

**Comment by berkerpeksag** [comment]
Thanks for the report, but this issue tracker is for www.python.org only. This was also reported on [python-dev](https://mail.python.org/pipermail/python-dev/2015-August/141136.html) and should be fixed by now(at least I can clone the repo successfully).

**Comment by native-api** [comment]
Okay, could you give me a contact for hg.python.org? There's completely nothing of the kind at the site itself or on the Web, and I'm still having this issue. (At the very least, I'll ask them to publish some contact-like information on the site)

**Comment by lac22** [comment]
Native-api I would send mail to infrastructure@python.org
https://mail.python.org/mailman/listinfo/infrastructure

**Comment by berkerpeksag** [comment]
You can also ask on the #python-infra IRC channel (freenode).
